[phases.install]
cmds = [
  "cd backend && npm install --omit=dev",
  "cd backend && npx prisma generate"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd backend && npx prisma migrate deploy"
]

[start]
cmd = "cd backend && npm run start:prod"

