[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "cd backend && npx prisma generate"
]

[phases.build]
cmds = [
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm run start:prod"

